repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # # The name of the repository. Changing this will rename the repository
  # name: 7mind-ios-v2

  # # A short description of the repository that will show up on GitHub
  # description: The official 7Mind iOS app.

  # A URL with more information about the repository
  # homepage: https://example.github.io/

  # Either `true` to make the repository private, or `false` to make it public.
  private: true

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false

  # Updates the default branch for this repository.
  default_branch: develop

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: false

# Labels for Issues and Pull Requests
labels:
  # type
  - name: bug
    description: Something isn't working
    color: 0074d9
  - name: enhancement
    description: New feature or request
    color: 0074d9
  - name: refactoring # improvement that doesn't change functionality
    description: improvement that doesn't change functionality
    color: 0074d9
  - name: research
    color: 0074d9
  - name: epic
    color: 0074d9
  - name: deployment
    description: Update to how application is deployed
    color: 0074d9
  - name: QA
    description: Dedicated QA request
    color: 0074d9

  # state
  - name: wip
    color: ffdc00
    oldname: WIP
  - name: design required
    description: Design work blocking implementation
    color: ff7e42
  - name: help wanted
    color: 2ecc40
  - name: duplicate
    description: This issue or pull request already exists
    color: aaaaaa
  - name: invalid
    description: This doesn't seem right
    color: aaaaaa
  - name: dependent
    color: aaaaaa
  - name: to estimate
    color: f5a623
  - name: to next sprint
    color: f45aea
  - name: to be discussed
    color: f7839a
  - name: mid-sprint
    description: This issue was added after the sprint started, it smells a little bit
    color: 8ab513


  # priority
  - name: prio high
    description: Next Release
    color: f4e2ab
    oldname: Prio High
  - name: prio hot
    description: Very urgent, release asap
    color: f4e2ab
    oldname: Prio Hot
  - name: prio low
    description: No release date
    color: f4e2ab
    oldname: Prio Low

  # story points
  - name: sp 1
    description: Few line fix < 1h, no testing
    color: b60205
    oldname: SP 1
  - name: sp 2
    description: Very small feature + test, < 2h
    color: b60205
    oldname: SP 2
  - name: sp 3
    description: Small feature + test, < 4h
    color: b60205
    oldname: SP 3
  - name: sp 5
    description: Feature + test, < 6h
    color: b60205
    oldname: SP 5
  - name: sp 8
    description: Uncertain feature, > 8h
    color: b60205
    oldname: SP 8
  - name: sp 13
    description: Big uncertain feature, < 2d ~> split
    color: b60205
    oldname: SP 13

  # Project Tags
  - name: library-v3-mvp
    description: Part of the Library V3 MVP
    color: 24a6af
