name: 'Helm Deployment Update'
description: 'Override image.tag'

inputs:

  helm-github-repo:
    description: 'URL path of the repository holding the helm chart definitions in the format sevenmind/kubernetes'
    required: true
  helm-repo-branch:
    description: 'Helm repo branch to work on'
    required: true
    default: master
  deploy-environment:
    description: 'Environment to deploy to'
    required: false
    default: production
  deploy-image-tag:
    description: 'new image tag to deploy to environment'
    required: true
  github-deployment-id:
    description: identifier of the tracking deployment
    required: false
  chart-path:
    description: 'Path inside the helm-repo to a specific chart'
    required: false
    default: "/"
  GITHUB_TOKEN:
    description: 'Github Token to clone repo'
    required: true

outputs: {}
  # random-number:
  #   description: "Random number"
  #   value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:

    - name: Clone helm repository
      shell: bash
      run: |
        echo "🚀 cloning helm repository"
        git config --global user.name "Deployment"
        git config --global user.email "benjamin@themothernature.app"
        git clone --depth 1 --single-branch --branch ${{ inputs.helm-repo-branch }} https://$GITHUB_ACTOR:${{ inputs.GITHUB_TOKEN }}@github.com/${{ inputs.helm-github-repo }}.git $GITHUB_WORKSPACE/helm

    - name: Apply override
      shell: bash
      run: |
        echo "🚀 applying override"
        cat << EOF > helm/${{ inputs.chart-path }}/values-${{ inputs.deploy-environment }}-tag.yaml
        image:
          tag: ${{ inputs.deploy-image-tag }}
        postUpgradeHook:
          deploymentId: "${{ inputs.github-deployment-id }}"
        EOF

    - name: Commit and push
      shell: bash
      working-directory: helm
      run: |
        echo "🚀 commit & push"
        git add -A
        git commit -m "New Deployment"
        git push

