name: 'Hello World'
description: 'Greet someone'

inputs:

  helm-repo-url-path:
    description: 'URL path of the repository holding the helm chart definitions in the format sevemind/kubernetes'
    required: true
  helm-repo-branch:
    description: 'Helm repo branch to work on'
    required: true
    default: master
  chart-path:
    description: 'Path inside the helm-repo to a specific chart'
    required: false
    default: "/"
  override-key:
    description: 'key to override'
    required: true
    default: 'image.tag'
  override-value:
    description: 'value to override'
    required: true
  GITHUB_TOKEN:
    description: 'Github Token to clone repo'
    required: true

outputs: {}
  # random-number:
  #   description: "Random number"
  #   value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:

    - name: Clone helm repository
      shell: bash
      run: |
        echo "cloning helm repository"
        git config --global user.name "Deployment"
        git config --global user.email "deploy-bot@7mind.de"
        git clone --depth 1 --single-branch --branch ${{ inputs.helm-repo-branch }} https://$GITHUB_ACTOR:${{ inputs.GITHUB_TOKEN }}@github.com/${{ inputs.helm-repo-url-path }}.git $GITHUB_WORKSPACE/helm

    - name: Apply override
      shell: bash
      run: |
        echo "applying override"
        echo "${{ inputs.override-key }}: ${{ inputs.override-value }}" >> helm/${{ inputs.chart-path }}/values-override.yaml

    - name: Commit and push
      shell: bash
      working-directory: helm
      run: |
        echo "commit & push"
        git add -A
        git commit -m "New Deployment"
        git push


    # - id: random-number-generator
    #   run: echo "::set-output name=random-id::$(echo $RANDOM)"
    #   shell: bash
    # - run: ${{ github.action_path }}/goodbye.sh
    #   shell: bash
