name: 'Hello World'
description: 'Greet someone'

inputs:

  helm-repo-url-path:
    description: 'URL path of the repository holding the helm chart definitions in the format sevemind/kubernetes'
    required: true
  helm-repo-branch:
    description: 'Helm repo branch to work on like refs/heads/release'
    required: true
    default: refs/heads/release
  chart-path:
    description: 'Path inside the helm-repo to a specific chart'
    required: false
    default: "/"
  override-key:
    description: 'key to override'
    required: true
    default: 'image.tag'
  override-value:
    description: 'value to override'
    required: true
  GITHUB_TOKEN:
    description: 'Github Token to clone repo'
    required: true

outputs: {}
  # random-number:
  #   description: "Random number"
  #   value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@master
      with:
        name: ${{ inputs.helm-repo-url-path }}.git
        ref: refs/heads/argo
        path: 'helm'
        fetch-depth: 1

    # - id: random-number-generator
    #   run: echo "::set-output name=random-id::$(echo $RANDOM)"
    #   shell: bash
    # - run: ${{ github.action_path }}/goodbye.sh
    #   shell: bash
